// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('clientsApp').controller('ClientsCtrl', function($scope, Clients) {
    $scope.clients = [];
    $scope.percentageOf = function(percentage) {
      return percentage * 100;
    };
    Clients.all().success(function(data) {
      return $scope.clients = data;
    });
    $scope.create = function() {
      return Clients.create($scope.newClient).success(function(data) {
        $scope.clients.push(data);
        return $scope.newClient = null;
      });
    };
    $scope.edit = function(client) {
      return $scope.activeClient = client;
    };
    $scope.update = function(client) {
      return Clients.update(client).success(function(data) {
        return $scope.activeClient = null;
      });
    };
    return $scope["delete"] = function(client) {
      return Clients["delete"](client.id).success(function(data) {
        var index;
        index = $scope.clients.indexOf(client);
        return $scope.clients.splice(index, 1);
      });
    };
  });

}).call(this);
