// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('clientsApp').controller('clientsCtrl', function($scope) {
    $scope.clients = [
      {
        id: 1,
        name: 'John',
        age: 25,
        percentage: 0.3
      }, {
        id: 2,
        name: 'Jane',
        age: 39,
        percentage: 0.18
      }, {
        id: 3,
        name: 'Jude',
        age: 51,
        percentage: 0.54
      }, {
        id: 4,
        name: 'James',
        age: 18,
        percentage: 0.32
      }, {
        id: 5,
        name: 'Javier',
        age: 47,
        percentage: 0.14
      }
    ];
    $scope.percentageOf = function(percentage) {
      return percentage * 100;
    };
    $scope["delete"] = function(client) {
      var index;
      index = $scope.clients.indexOf(client);
      return $scope.clients.splice(index, 1);
    };
    return $scope.create = function() {
      $scope.newClient.id = $scope.clients.length + 1;
      $scope.clients.push($scope.newClient);
      return $scope.newClient = null;
    };
  });

}).call(this);
