// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('clientsApp').factory('Clients', function($http, $log) {
    var BASE_URL;
    BASE_URL = 'http://localhost:3005/clients';
    return {
      all: function() {
        return $http.get(BASE_URL);
      },
      create: function(client) {
        return $http.post(BASE_URL, client);
      },
      update: function(client) {
        return $http.put(BASE_URL + '/' + client.id, client);
      },
      "delete": function(id) {
        return $http["delete"](BASE_URL + '/' + id);
      }
    };
  });

}).call(this);
