// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('clientsApp').directive('clientRow', function() {
    return {
      restrict: 'A',
      templateUrl: 'client.html',
      link: function(scope, element, attrs) {
        scope.isEditing = false;
        scope.editClient = function() {
          scope.original = angular.copy(scope.client);
          return scope.isEditing = true;
        };
        scope.updateClient = function() {
          scope.update(scope.client);
          return scope.isEditing = false;
        };
        scope.deleteClient = function() {
          return scope.dedele(scope.client);
        };
        return scope.cancelEdit = function() {
          scope.isEditing = false;
          return angular.copy(scope.original, scope.client);
        };
      }
    };
  });

}).call(this);
