// Generated by CoffeeScript 1.10.0
(function() {
  var INTEGER_REGEXP;

  INTEGER_REGEXP = /^\-?\d+$/;

  angular.module('clientsApp').directive('integer', function() {
    return {
      require: 'ngModel',
      link: function(scope, elm, attrs, ctrl) {
        return ctrl.$validators.integer = function(modelValue, viewValue) {
          if (ctrl.$isEmpty(modelValue)) {
            return true;
          }
          if (INTEGER_REGEXP.test(viewValue)) {
            return true;
          }
          return false;
        };
      }
    };
  });

}).call(this);
