// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('clientsApp').filter('percentage', function($filter) {
    return function(value) {
      return $filter('number')(value * 100, 0) + ' %';
    };
  });

}).call(this);
